### ISSUE TITLE
PPA Url out of date for new controller version

### ISSUE THREAD

**Issue by phcyso** [sous-chefs/unifi#1]
Hi, it looks like Ubiquiti are moving to a slightly more sane PPA address for the newer versions.
Blog post:
http://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-4-6-6-is-released/ba-p/1288816

```
The new instructions for 4.6.6 says:
## Debian/Ubuntu
# stable => unifi4
# deb http://www.ubnt.com/downloads/unifi/debian unifi4 ubiquiti
deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti
```

**Comment by phcyso** [comment]
Created pull request #2

**Comment by mjuarez** [comment]
Looks like @ampledata merged this in awhile ago. Closing issue out.
